apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-api
  namespace: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-api
  template:
    metadata:
      labels:
        app: hello-api
    spec:
      containers:
      - name: hello-api
        image: <your-dockerhub-username>/hello-api:latest
        envFrom:
        - configMapRef:
            name: app-config
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-api
  namespace: hello-app
spec:
  type: LoadBalancer
  selector:
    app: hello-api
  ports:
  - port: 80
    targetPort: 8080
